version: '3'
services:
  sample-project:
    container_name: sample-project
    image: sample-project
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
